# Create a dictionary for "Reason for moving"
reason_for_moving_dict <- list(
  `0` = "NIU",
  `1` = "Change in marital status",
  `2` = "To establish own household",
  `3` = "Other family reason",
  `4` = "New job or job transfer",
  `5` = "To look for work or lost job",
  `6` = "For easier commute",
  `7` = "Retired",
  `8` = "Other job-related reason",
  `9` = "Wanted to own home, not rent",
  `10` = "Wanted new or better housing",
  `11` = "Wanted better neighborhood",
  `12` = "For cheaper housing",
  `13` = "Other housing reason",
  `14` = "Attend/leave college",
  `15` = "Change of climate",
  `16` = "Health reasons",
  `17` = "Other reasons",
  `18` = "Natural disaster",
  `19` = "Foreclosure or eviction",
  `20` = "Relationship with unmarried partner"
)

# Create a dictionary for "State of residence 1 year ago"
state_residence_dict <- list(
  `0` = "NIU",
  `1` = "Alabama",
  `2` = "Alaska",
  `4` = "Arizona",
  `5` = "Arkansas",
  `6` = "California",
  `8` = "Colorado",
  `9` = "Connecticut",
  `10` = "Delaware",
  `11` = "District of Columbia",
  `12` = "Florida",
  `13` = "Georgia",
  `15` = "Hawaii",
  `16` = "Idaho",
  `17` = "Illinois",
  `18` = "Indiana",
  `19` = "Iowa",
  `20` = "Kansas",
  `21` = "Kentucky",
  `22` = "Louisiana",
  `23` = "Maine",
  `24` = "Maryland",
  `25` = "Massachusetts",
  `26` = "Michigan",
  `27` = "Minnesota",
  `28` = "Mississippi",
  `29` = "Missouri",
  `30` = "Montana",
  `31` = "Nebraska",
  `32` = "Nevada",
  `33` = "New Hampshire",
  `34` = "New Jersey",
  `35` = "New Mexico",
  `36` = "New York",
  `37` = "North Carolina",
  `38` = "North Dakota",
  `39` = "Ohio",
  `40` = "Oklahoma",
  `41` = "Oregon",
  `42` = "Pennsylvania",
  `44` = "Rhode Island",
  `45` = "South Carolina",
  `46` = "South Dakota",
  `47` = "Tennessee",
  `48` = "Texas",
  `49` = "Utah",
  `50` = "Vermont",
  `51` = "Virginia",
  `53` = "Washington",
  `54` = "West Virginia",
  `55` = "Wisconsin",
  `56` = "Wyoming",
  `91` = "Abroad",
  `99` = "Same house"
)

# Replace numeric codes with labels in the dataset
data_movers_only$WHYMOVE <- reason_for_moving_dict[as.character(data_movers_only$WHYMOVE)]
data_movers_only$MIGSTA1 <- state_residence_dict[as.character(data_movers_only$MIGSTA1)]

data_movers_only$YEAR <- as.character(data_movers_only$YEAR)
data_movers_only$MIGSTA1 <- as.character(data_movers_only$MIGSTA1)
data_movers_only$WHYMOVE <- as.character(data_movers_only$WHYMOVE)